SchoolJournal/SchoolJournal/Controllers/SearchPupilController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolJournal.Data.Repos;

namespace SchoolJournal.Controllers
{
    public class SearchPupilController : Controller
    {
        private IPupilRepository _pupilRepository;

        public SearchPupilController(IPupilRepository pupilRepository)
        {
            _pupilRepository = pupilRepository;
        }

        [HttpGet]
        public IActionResult Search()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Search(Models.SearchPupil model)
        {
            var pupils = await _pupilRepository.Search(model.SearchText);
            model.Pupils = pupils;
            return View(model);
        }
    }
}

SchoolJournal/SchoolJournal/Controllers/StreamsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SchoolJournal.Data.Repos;

namespace SchoolJournal.Controllers
{
    public class StreamsController : Controller
    {
        private IStreamRepository _streamRepository;

        public StreamsController(IStreamRepository streamRepository)
        {
            _streamRepository = streamRepository;
        }

        // GET: Streams
        public async Task<IActionResult> Index()
        {
            return View(await _streamRepository.GetAll());              
        }

        // GET: Streams/Create Метод для отображения формы создания нового потока
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Streams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Started,CurrentClass,IsCompleted")] Models.DB.Stream stream)        
        {
            if (ModelState.IsValid)
            {
                await _streamRepository.Create(stream);
                return RedirectToAction(nameof(Index));
            }
            return View(stream);
        }

        // GET: Streams/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null) return NotFound();

            var stream = await _streamRepository.GetById(id);
            if (stream == null) return NotFound();
            return View(stream);            
        }

        // POST: Streams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,Started,CurrentClass,IsCompleted")] Models.DB.Stream stream)
        {
            if (ModelState.IsValid)
            {
                await _streamRepository.Update(stream);
                return RedirectToAction(nameof(Index));
            }
            return View(stream);
        }

        // GET: Streams/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null) return NotFound();

            var stream = await _streamRepository.GetById(id);
            if (stream == null) return NotFound();
            return View(stream);
        }

        // POST: Streams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _streamRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }
        
        // GET: Streams/Details/5 Показываем список учеников в потоке
        public async Task<IActionResult> Details(Guid? id)
        {
            return RedirectToAction("Index", "Pupils", new { streamId = id });            
        }
    }
}

SchoolJournal/SchoolJournal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SchoolJournal.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Школьный журнал</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                        
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated == false)
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Вход на сайт</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Выход</a>
                            }
                        </li>                                             
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Streams" asp-action="Index">Потоки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SearchPupil" asp-action="Search">Поиск ученика</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">&copy;@DateTime.Today.Year - Школьный Журнал</div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>